---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Producers & Remixers Organization"
keywords:    "Producing, music, electronic, DAW, club, remixing"
description: "Official website for the Producers & Remixers Organization"
source_link: "http://producersandremixers.org"
favicon:     "favicon.ico"
touch_icon:  "favicon.ico"
google_analytics_key:  UA-37926982-10


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
