
$.extend($.easing,
{
    def: 'easeOutQuad',
    easeInOutExpo: function (x, t, b, c, d) {
        if (t==0) return b;
        if (t==d) return b+c;
        if ((t/=d/2) < 1) return c/2 * Math.pow(2, 10 * (t - 1)) + b;
        return c/2 * (-Math.pow(2, -10 * --t) + 2) + b;
    }
});

(function( $ ) {

    var settings;
    var disableScrollFn = false;
    var navItems;
    var navs = {}, sections = {};

    $.fn.navScroller = function(options) {
        settings = $.extend({
            scrollToOffset: 170,
            scrollSpeed: 800,
            activateParentNode: true,
        }, options );
        navItems = this;

        //attatch click listeners
    	navItems.on('click', function(event){
    		event.preventDefault();
            var navID = $(this).attr("href").substring(1);
            disableScrollFn = true;
            activateNav(navID);
            populateDestinations(); //recalculate these!
        	$('html,body').animate({scrollTop: sections[navID] - settings.scrollToOffset},
                settings.scrollSpeed, "easeInOutExpo", function(){
                    disableScrollFn = false;
                }
            );
    	});

        //populate lookup of clicable elements and destination sections
        populateDestinations(); //should also be run on browser resize, btw

        // setup scroll listener
        $(document).scroll(function(){
            if (disableScrollFn) { return; }
            var page_height = $(window).height();
            var pos = $(this).scrollTop();
            for (i in sections) {
                if ((pos + settings.scrollToOffset >= sections[i]) && sections[i] < pos + page_height){
                    activateNav(i);
                }
            }
        });
    };

    function populateDestinations() {
        navItems.each(function(){
            var scrollID = $(this).attr('href').substring(1);
            navs[scrollID] = (settings.activateParentNode)? this.parentNode : this;
            sections[scrollID] = $(document.getElementById(scrollID)).offset().top;
        });
    }

    function activateNav(navID) {
        for (nav in navs) { $(navs[nav]).removeClass('active'); }
        $(navs[navID]).addClass('active');
    }
})( jQuery );


$(document).ready(function (){

    $('nav li a').navScroller();

    //section divider icon click gently scrolls to reveal the section
	$(".sectiondivider").on('click', function(event) {
    	$('html,body').animate({scrollTop: $(event.target.parentNode).offset().top - 50}, 400, "linear");
	});

    //links going to other sections nicely scroll
	$(".container a").each(function(){
        if ($(this).attr("href").charAt(0) == '#'){
            $(this).on('click', function(event) {
        		event.preventDefault();
                var target = $(event.target).closest("a");
                var targetHight =  $(target.attr("href")).offset().top
            	$('html,body').animate({scrollTop: targetHight - 170}, 800, "easeInOutExpo");
            });
        }
	});

});


// Delay Time Scripts: js/delaytime.js
// Generated by gencontent.pl - Saturday, April 1, 2017 - 6:14 AM

    function checkNumber(input, min, max, msg) {
        msg = msg + " field has invalid data: " + input.value;
        var str = input.value;
        for (var i = 0; i < str.length; i++) {
            var ch = str.substring(i, i + 1);
            if ((ch < "0" || "9" < ch) && ch != ".") {
                alert(msg);
                return false;
            }
        }
        var num = 0 + str;
        if (num < min || max < num) {
            alert(msg + " not in range [" + min + ".." + max + "]");
            return false;
        }
        input.value = str;
        return true;
    }

     function computeField(input) {
        if (input.value !== null && input.value.length !== 0) {
            input.value = "" + input.value;
        }
        computeForm(input.form);
    }

    function computeForm(form) {
        form.bpm.value = parseFloat(form.bpm.value);
        if ((form.bpm.value == null || form.bpm.value.length == 0)) {
            form.delaytime.value = "Enter BPM";
            return;
        }
        if (!checkNumber(form.bpm, 1, 480, "BPM")) {
            form.delaytime.value = "Invalid";
            return;
        }
        var sec = 1;
        sec = 60 / form.bpm.value;
        var notevalueval=form.notevalue.value;
        if (notevalueval == "1W") {
            var noteval = .25;
        }
        if (notevalueval == "2") {
            var noteval = .5;
        }
        if (notevalueval == "2T") {
            var noteval = .75;
        }
        if (notevalueval == "4") {
            var noteval = 1;
        }
        if (notevalueval == "4T") {
            var noteval = 1.5;
        }
        if (notevalueval == "8") {
            var noteval = 2;
        }
        if (notevalueval == "8T") {
            var noteval = 3;
        }
        if (notevalueval == "16") {
            var noteval = 4;
        }
        if (notevalueval == "16T") {
            var noteval = 6;
        }
        if (notevalueval == "32") {
            var noteval = 8;
        }
        if (notevalueval == "32T") {
            var noteval = 12;
        }
        if (notevalueval == "64") {
            var noteval = 16;
        }
        form.delaytime.value = (1 / noteval * sec) * 1000;
        var dotnoteval=form.dotnote.value;
        if (dotnoteval == "YES") {
            form.delaytime.value = form.delaytime.value * 1.5;
        }
        form.delaytime.value = parseInt(form.delaytime.value)
    }

    function clearForm(form) {
        form.bpm.value = "";
        form.delaytime.value = "";
        return;
    }
// Generated by gencontent.pl END
